### ISSUE TITLE
Issues after installation

### ISSUE THREAD

**Issue by cschlaefcke** [mjstealey/vault-consul-docker#4]
Hi @mjstealey,

thank you for your great project and the awesome documentation!! I am a Hashicorp Terraform/Vault/Consul beginner and aiming to achieve managed ssh certificate access to my cloud landscape with the Hashicorp tools.

I was struggeling with the Hashicorp Vault docker image in the beginning having trouble to get it initialized/unsealed. Your project and your great documentation helped me to close this gap 👍 

Now I have dockerized vault and consul running (proxied with nginx), initialized and unsealed and the initial commands are working:
```
$ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.1.2
Cluster Name    vault-cluster-931f92e4
Cluster ID      8b9f8118-ea70-286d-6f29-84c687f8a900
HA Enabled      true
HA Cluster      https://consul:444
HA Mode         active

$ vault kv put kv/my-secret my-value=s3cr3t
Success! Data written to: kv/my-secret

$ vault kv get kv/my-secret
====== Data ======
Key         Value
---         -----
my-value    s3cr3t
```

But when I try to vault kv list kv/ I only get this:
```
$ vault kv list kv/
No value found at kv/
```
Also the consul ui is not showing the expected key/value entry:
<img width="500" alt="Consul UI" src="https://user-images.githubusercontent.com/3392847/57448438-aa84da80-7259-11e9-894c-71f3d9dcd486.png">
... as same as the Vault UI:
<img width="500" alt="Vault UI" src="https://user-images.githubusercontent.com/3392847/57448687-4adaff00-725a-11e9-94d4-35e40e287d33.png">

But whenever I run:
```
$ vault kv get kv/my-secret
====== Data ======
Key         Value
---         -----
my-value    s3cr3t
```
... the key/value is obviously there. 😥 

Do you have any idea what could lead to this behaviour? Any hint pointing me to the right direction would be very much appriciated!

Thank you & Best Regards,

Christian

**Comment by mjstealey** [comment]
@cschlaefcke - thank you for the kind words :-)

I'll spin up a CentOS VM and have a look quick.
Off the top of my head there are two things I can think of that are worth checking.

1. Did you explicitly declare the kv version to use? 
    - i.e. `vault secrets enable -version=1 kv` 
    - ref: https://www.vaultproject.io/docs/secrets/kv/index.html
2. Is there any difference in the list call between using `kv/` and `/kv`? 
    - i.e. `vault kv list /kv`

**Comment by cschlaefcke** [comment]
@mjstealey - you´re welcome

regarding 1. yes (copied´n´pasted from your docs):
<img width="250" alt="Bildschirmfoto 2019-05-09 um 16 59 37" src="https://user-images.githubusercontent.com/3392847/57463872-ecbf1380-727b-11e9-8aed-4c597785e00e.png">

regarding 2. - no difference:
```
$ vault kv list /kv
No value found at kv/

$ vault kv list kv
No value found at kv/
```

Could it be that consul requires some extra ACL policies/rules in order for vault to handle this?

**Comment by cschlaefcke** [comment]
Hi @mjstealey 

I was able to narrow down my problem a little bit. Your setup is working fine - the issue comes with my nginx reverse proxy approach. When I call consul/vault with the direkt URLs (e.g. http://localhost:8200(9200), http://localhost:9500) everything works like expected. 
The thing that is strange is, that vault status, secret, put, get also work via my nginx based reverse proxy (e.g. https://vault.example.com, https://consul.example.com) only list and the web/ui frontend are refusing to return anything useful.

If you anyway have a hint about how to solve my issue it would be great. I already learned that the reverse-proxying via nginx (which I am still using most of the time in combination with my docker env) does not seem to be state of the art when using consul/vault.

Thank you & Best Regards,

Christian

**Comment by mjstealey** [comment]
@cschlaefcke - Consul can be very finicky about networking, especially in docker, so there might be something to how Consul "sees" the reverse proxy that it doesn't like and is not allowing vault to poke through on the `list` request... 

I still plan to spin up a CentOS environment outside of my local machine and have a look, just haven't had the cycles to do so yet.

Will update back to this issue once I get some time to dig in.

**Comment by cschlaefcke** [comment]
That would be great! 👍
